### PR TITLE
simplify fallback paths

### PR DESCRIPTION
**Pull request by grosser**
@StephenPancake

### CODE REVIEW

**Review by StephenPancake — APPROVED** [review]

**Comment by StephenPancake** [comment]
Yeah, that's a lot cleaner.

PR #10 was both my first OSS contribution and my first Rust code.

**Comment by grosser** [comment]
awesome :D

... I failed to run `cargo build --release --target x86_64-apple-darwin`
so I just pushed the new version, is that good enough for you ?

**Comment by StephenPancake** [comment]
`cargo build --release --target x86_64-apple-darwin` worked locally for me, but we're pulling based on release in our containers. Do we need a 0.2.0 tag?

**Comment by grosser** [comment]
pushed the tag

**Pull request merged**
